### ISSUE TITLE
FileNotFoundError: No file '../graphics/test/rock.png' found in working directory

### ISSUE THREAD

**Issue by ShivamKR12** [clear-code-projects/Zelda#18]
Traceback (most recent call last):
  File "c:\Users\Shivam\Desktop\voxel 3d\Zelda-main\01 - level\1 - level\code\main.py", line 29, in <module>
    game = Game()
           ^^^^^^
  File "c:\Users\Shivam\Desktop\voxel 3d\Zelda-main\01 - level\1 - level\code\main.py", line 14, in __init__
    self.level = Level()
                 ^^^^^^^
  File "c:\Users\Shivam\Desktop\voxel 3d\Zelda-main\01 - level\1 - level\code\level.py", line 18, in __init__
    self.create_map()
  File "c:\Users\Shivam\Desktop\voxel 3d\Zelda-main\01 - level\1 - level\code\level.py", line 26, in create_map
    Tile((x,y),[self.visible_sprites,self.obstacle_sprites])
  File "c:\Users\Shivam\Desktop\voxel 3d\Zelda-main\01 - level\1 - level\code\tile.py", line 7, in __init__
    self.image = pygame.image.load('../graphics/test/rock.png').convert_alpha()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: No file '../graphics/test/rock.png' found in working directory 'C:\Users\Shivam\Desktop\voxel 3d\Zelda-main'.

**Comment by ShivamKR12** [comment]
Traceback (most recent call last):
  File "c:\Users\Shivam\Desktop\voxel 3d\Zelda-main\01 - level\1 - level\code\main.py", line 29, in <module>
    game = Game()
           ^^^^^^
  File "c:\Users\Shivam\Desktop\voxel 3d\Zelda-main\01 - level\1 - level\code\main.py", line 14, in __init__
    self.level = Level()
                 ^^^^^^^
  File "c:\Users\Shivam\Desktop\voxel 3d\Zelda-main\01 - level\1 - level\code\level.py", line 18, in __init__
    self.create_map()
  File "c:\Users\Shivam\Desktop\voxel 3d\Zelda-main\01 - level\1 - level\code\level.py", line 26, in create_map
    Tile((x,y),[self.visible_sprites,self.obstacle_sprites])
  File "c:\Users\Shivam\Desktop\voxel 3d\Zelda-main\01 - level\1 - level\code\tile.py", line 7, in __init__
    self.image = pygame.image.load('../graphics/test/rock.png').convert_alpha()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: No file '../graphics/test/rock.png' found in working directory 'C:\Users\Shivam\Desktop\voxel 3d\Zelda-main'.

**Comment by ShivamKR12** [comment]
Traceback (most recent call last):
  File "c:\Users\Shivam\Desktop\voxel 3d\Zelda-main\01 - level\1 - level\code\main.py", line 29, in <module>
    game = Game()
           ^^^^^^
  File "c:\Users\Shivam\Desktop\voxel 3d\Zelda-main\01 - level\1 - level\code\main.py", line 14, in __init__
    self.level = Level()
                 ^^^^^^^
  File "c:\Users\Shivam\Desktop\voxel 3d\Zelda-main\01 - level\1 - level\code\level.py", line 18, in __init__
    self.level = Level()
                 ^^^^^^^
  File "c:\Users\Shivam\Desktop\voxel 3d\Zelda-main\01 - level\1 - level\code\level.py", line 18, in __init__
    self.create_map()
  File "c:\Users\Shivam\Desktop\voxel 3d\Zelda-main\01 - level\1 - level\code\level.py", line 26, in create_map
    Tile((x,y),[self.visible_sprites,self.obstacle_sprites])
  File "c:\Users\Shivam\Desktop\voxel 3d\Zelda-main\01 - level\1 - level\code\tile.py", line 7, in __init__
    self.image = pygame.image.load('graphics/test/rock.png').convert_alpha()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: No file 'graphics/test/rock.png' found in working directory 'C:\Users\Shivam\Desktop\voxel 3d\Zelda-main'.

**Comment by rralen** [comment]
yo lo arregle meramente poniendo las rutas completas me funciono aunque fue tardado asi que al final para ahorarrme problemas ya que solo era para jugar saque todo de las carpetas y puse el nombre tal cual

**Comment by ShivamKR12** [comment]
@rralen  sorry my friend but i am unable to understand your language?
could you please tell me which language do you speak?

**Comment by ShivamKR12** [comment]
if you mean "I fixed it simply by using the full paths; it worked for me, although it was time-consuming. In the end, to avoid problems since it was only for playing, I removed everything from the folders and put the name exactly as it was." , then thanks for your kind suggestion but i believe it is not a permanent fix.

**Comment by mbomb007** [comment]
You need to run `main.py` from the `code` directory for the game to run.

Example for Linux:

```bash
cd "15 - fixes audio/code"
python3 main.py
```

**Comment by ShivamKR12** [comment]
@mbomb007 
ya, it worked. but trying to cd into code is not really possible on windows since you will get the error 
"PS C:\Users\Shivam\AppData\Local\Programs\Python\Python312> cd voxel 3d\Zelda-main\01 - level\1 - level\code        
Set-Location : A positional parameter cannot be found that accepts argument '3d\Zelda-main\01'.
At line:1 char:1
+ cd voxel 3d\Zelda-main\01 - level\1 - level\code
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-Location], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.SetLocationCommand" .

so, you will just have to open the terminal on the folder itself by right clicking and opening terminal.

**Comment by mbomb007** [comment]
> trying to cd into code is not really possible on windows

This is incorrect. Just surround the path with quotation marks.

This works in PowerShell:

```ps1
cd '.\projects\pygame\zelda-main\15 - fixes audio\code'
```
