### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by iaZe** [clear-code-projects/Zelda#6]
When trying to run a main.py I come across the following error
```Traceback (most recent call last):
  File "c:\Users\Kali\Desktop\15 - fixes audio\code\main.py", line 37, in <module>
    game = Game()
  File "c:\Users\Kali\Desktop\15 - fixes audio\code\main.py", line 14, in __init__
    self.level = Level()
  File "c:\Users\Kali\Desktop\15 - fixes audio\code\level.py", line 23, in __init__
    self.visible_sprites = YSortCameraGroup()
  File "c:\Users\Kali\Desktop\15 - fixes audio\code\level.py", line 170, in __init__
    self.floor_surf = pygame.image.load('../graphics/tilemap/ground.png').convert()
FileNotFoundError: No file '../graphics/tilemap/ground.png' found in working directory 'C:\Users\Kali'.```

**Comment by VantaTree** [comment]
The issues tab is not for asking help, it's used to report things like bugs.

If can get help from the community from Clear Code's discord: https://discord.com/invite/a5C6pYw2w5
